### PR TITLE
Add foreign key for campaign.company_id

### PR DESCRIPTION
**Pull request by Nnachevvv**
Implements #374
After execution, the campaign table contains `campaigns_company_id_fkey` as constraint:
```
 constraint_catalog | constraint_schema |             constraint_name             | table_catalog | table_schema |       table_name        | constraint_type | is_deferrable | initially_deferred | enforced
 postgres           | api               | campaigns_company_id_fkey               | postgres      | api          | campaigns               | FOREIGN KEY     | NO            | NO                 | YES
```

### CODE REVIEW

**Review by igoychev — APPROVED** [review]
quick and tidy! thank you!

**Comment by kachar** [comment]
@Nnachevvv Was there a need to change `schema.prisma` file or the migration was enough? I don't see such diff in the PR

**Comment by Nnachevvv** [comment]
@kachar I think this field has been already added in our schema before:
https://github.com/podkrepi-bg/api/blob/d75283f2b172ec61c1845e534cec78016df24479/schema.prisma#L203


The command `yarn prisma db pull` only aligns the lines, so I think the migration is enough, but I maybe be wrong

**Comment by kachar** [comment]
Ah, so the field has been added but without a migration, and now we add the migration. Thanks for clarifying that and kudos for your efforts. 🚀

**Pull request merged**
